[package]
name = "arduino-micro-examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
panic-halt = "1.0.0"

[dependencies.arduino-hal]
path = "../../arduino-hal/"
features = ["arduino-micro"]
