[package]
name = "sparkfun-promicro-examples"
version = "0.0.0"
authors = ["Rahix <rahix@rahix.de>"]
edition = "2021"
publish = false

[dependencies]
panic-halt = "1.0.0"
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "1.0"
usb-device = "0.3.2"
usbd-serial = "0.2.2"

[dependencies.arduino-hal]
path = "../../arduino-hal/"
features = ["sparkfun-promicro"]
